site_name: Rajat's Notes
site_url: https://im-rajat.github.io/Notes/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

docs_dir: 'docs'

markdown_extensions:
  - tables
  - sane_lists
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
